apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  admin.password: $2a$10$QuDxbjmfWyCzcaMsVZ4VDOjfIXUwD4p0/cegnGnkEFvIPcrDtCuO2
  admin.passwordMtime: 2019-06-12T03:12:51Z
  server.secretkey: SEVPSm9aVThKSXVWRW5tbFp5Sk4rK1p5RkZnUGhQMHB5VTZBWlJaN3RKUT0=
