apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: argo-cd-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jessesuen@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
