apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: argo-cd-issuer
    kind: Issuer
  commonName: argo-cd-kubecon.apps.argoproj.io
  dnsNames:
  - argo-cd-kubecon.apps.argoproj.io
  acme:
    config:
    - dns01:
        provider: clouddns-provider
      domains:
      - argo-cd-kubecon.apps.argoproj.io
