apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: argo-cd/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: argo-rollouts/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: argo-workflows/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argo

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tiller
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jessesuen/k8s-deployments.git
#     path: tiller
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-artifacts
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jessesuen/k8s-deployments.git
#     path: minio
#     plugin:
#       name: kustomized-helm
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
