apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: argo-cd/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: argo-rollouts/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: argo-workflows/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: argo

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    certmanager.k8s.io/disable-validation: "true"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  # annotations:
  #   argoccd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/jetstack/cert-manager.git
    path: deploy/charts/cert-manager
    #targetRevision: release-0.9
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ingress

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: nginx-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
    - /spec/clusterIP

---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-init
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: istio/init
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    path: istio/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle


# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: prometheus-operator

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-operator
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jessesuen/k8s-deployments.git
#     path: prometheus-operator
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: prometheus-operator

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: tiller
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jessesuen/k8s-deployments.git
#     path: tiller
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-artifacts
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/jessesuen/k8s-deployments.git
#     path: minio
#     plugin:
#       name: kustomized-helm
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: default
