apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.dev.argoproj.io

  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: f924b0c994fa91846095
          clientSecret: $dex.github.clientSecret
          orgs:
          - name: argoproj
            teams:
            - argo-cd-admins
