apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: prometheus-operator
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: http://$host/oauth2/start?rd=$request_uri
spec:
  rules:
  - host: grafana.dev.argoproj.io
    http:
      paths:  
      - backend:
          serviceName: prometheus-operator-grafana
          servicePort: 80
        path: /

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth
  namespace: prometheus-operator

---
apiVersion: v1
kind: Secret
metadata:
  name: istio-grafana-oauth
  namespace: istio-system

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: istio-grafana
  namespace: istio-system
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://$host/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: http://$host/oauth2/start?rd=$request_uri
spec:
  rules:
  - host: istio-grafana.dev.argoproj.io
    http:
      paths:  
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /
