apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-rollout
  template:
    metadata:
      labels:
        app: nginx-rollout
    spec:
      containers:
      - name: nginx-rollout
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "5"]
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
    nginx:
      ingress: nginx-rollout-ingress

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rollout-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: nginx-rollout

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nginx-rollout-ingress
spec:
  rules:
  - host: nginx-rollout.dev.argoproj.io
    http:
      paths:
      - backend:
          serviceName: nginx-rollout-svc
          servicePort: 80
        path: /
