apiVersion: v1
kind: Service
metadata:
  name: nginx-rollout-845d9c84c
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rollout
    name: nginx-rollout
    uid: add7da85-db6f-11e9-9d90-42010aa8009f
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: nginx-rollout
    rollouts-pod-template-hash: 845d9c84c

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rollout-849ccbf74c
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rollout
    name: nginx-rollout
    uid: add7da85-db6f-11e9-9d90-42010aa8009f
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: nginx-rollout
    rollouts-pod-template-hash: 849ccbf74c

---
# this would be a shadow copy by rollout controller
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-rollout-ingress-845d9c84c
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Rollout
    name: nginx-rollout
    uid: add7da85-db6f-11e9-9d90-42010aa8009f
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
spec:
  rules:
  - host: nginx-rollout.dev.argoproj.io
    http:
      paths:
      - backend:
          serviceName: nginx-rollout-845d9c84c
          servicePort: 80
        path: /
