apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm init --client-only && helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template . --name $ARGOCD_APP_NAME > all.yaml && kustomize build"]
