apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../jesse-dev

images:
- name: argoproj/argocd
  newName: jessesuen/argocd
  newTag: latest
- name: argoproj/argocd-ui
  newName: jessesuen/argocd-ui
  newTag: latest
