apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: workflow-controller
spec:
  template:
    spec:
      containers:
      - name: workflow-controller
        image: jessesuen/workflow-controller:latest
        args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - jessesuen/argoexec:latest

---
apiVersion: v1
kind: Service
metadata:
  name: argo-ui
spec:
  type: LoadBalancer
