apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: workflow-controller
  namespace: argo
spec:
  template:
    spec:
      containers:
      - name: workflow-controller
        image: jessesuen/workflow-controller:latest
        args:
        - --configmap
        - workflow-controller-configmap
        - --executor-image
        - jessesuen/argoexec:latest
