apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  revisionHistoryLimit: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  revisionHistoryLimit: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-controller
spec:
  revisionHistoryLimit: 3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-server
spec:
  revisionHistoryLimit: 3
