apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/k8s-deployments.git
    targetRevision: HEAD
    path: minikube/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo-rollouts.git
    targetRevision: stable
    path: manifests/cluster-install
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argo.git
    targetRevision: stable
    path: manifests/cluster-install
  destination:
    server: https://kubernetes.default.svc
    namespace: argo

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
spec:
  project: default
  source:
    repoURL: https://github.com/jessesuen/rollouts-demo-deployment.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
