apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- all.yaml

patchesStrategicMerge:
- make-bucket-job.yaml

patchesJson6902:
- target:
    group: batch
    version: v1
    kind: Job
    name: argo-artifacts-minio-make-bucket-job
  path: remove-helm-hooks.yaml
