bases:
#- github.com/argoproj/argo-cd//manifests/cluster-install?ref=release-0.10
#- github.com/argoproj/argo-cd//manifests/cluster-install
- github.com/jessesuen/argo-cd//manifests/cluster-install?ref=rbac-roles

patchesStrategicMerge:
- patches/jesse.yaml