apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- upstream.yaml
- argocd-namespace.yaml

patches:
- patches/argocd-server-service.yaml
- patches/argocd-secret.yaml

namespace: argocd

# images:
# - name: argoproj/argocd
#   newName: jessesuen/argocd
#   newTag: latest
# - name: argoproj/argocd-ui
#   newName: jessesuen/argocd-ui
#   newTag: latest
